# Generated by Django 2.2 on 2020-02-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='首图')),
                ('desc', models.CharField(max_length=20, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('article', models.TextField(max_length=200, verbose_name='文章')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('author', models.CharField(max_length=15, verbose_name='作者')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('introduction', models.CharField(max_length=200, verbose_name='简介')),
                ('img', models.ImageField(upload_to='public', verbose_name='公共图片')),
            ],
        ),
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='评论人')),
                ('email', models.EmailField(default='2641938505@qq.com', max_length=254, verbose_name='个人邮箱')),
                ('body', models.CharField(max_length=200, verbose_name='评论内容')),
                ('url', models.URLField(default='http://www.baidu.com', verbose_name='评论来源')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article', verbose_name='所属文章')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Public', verbose_name='共有内容'),
        ),
    ]
