# Generated by Django 2.2 on 2020-02-25 01:16

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
