# Generated by Django 2.2 on 2020-02-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200225_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=None, upload_to='article_imgs', verbose_name='图片'),
        ),
    ]
