# Generated by Django 2.2 on 2020-02-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default=0, upload_to='article_imgs', verbose_name='图片'),
        ),
    ]
