# Generated by Django 2.2 on 2020-02-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'ordering': ['-create_time'], 'verbose_name': '选项表', 'verbose_name_plural': '选项表'},
        ),
        migrations.AlterModelOptions(
            name='qusetion',
            options={'ordering': ['-create_date'], 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
    ]
