# Generated by Django 2.2 on 2020-02-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200217_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qusetion',
            options={'ordering': ['-create_date'], 'verbose_name': '投票表', 'verbose_name_plural': '投票表'},
        ),
        migrations.AlterField(
            model_name='choices',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='得票数'),
        ),
    ]
